create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','placement_manager');
create type public.profile_status as enum ('active','inactive');
create type public.organization_status as enum ('prospect','active','inactive');
create type public.card_priority as enum ('low','medium','high');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, email text not null, role public.user_role not null default 'placement_manager', status public.profile_status not null default 'active', created_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(), placement_manager_id uuid not null references public.profiles(id), name text not null, industry text, website text, city text, status public.organization_status not null default 'prospect', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.contacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, placement_manager_id uuid not null references public.profiles(id), name text not null, designation text, email text, phone text, linkedin_url text, notes text, created_at timestamptz not null default now());
create table public.meeting_reports (id uuid primary key default gen_random_uuid(), placement_manager_id uuid not null references public.profiles(id), organization_id uuid references public.organizations(id) on delete set null, contact_id uuid references public.contacts(id) on delete set null, meeting_date date not null, title text, summary text not null, action_items text, attendees text, created_at timestamptz not null default now());
create table public.kanban_stages (id uuid primary key default gen_random_uuid(), placement_manager_id uuid not null references public.profiles(id), name text not null, position integer not null default 0, color text not null default '#6b7280');
create table public.kanban_cards (id uuid primary key default gen_random_uuid(), stage_id uuid not null references public.kanban_stages(id) on delete cascade, placement_manager_id uuid not null references public.profiles(id), organization_id uuid references public.organizations(id) on delete set null, title text not null, description text, priority public.card_priority not null default 'medium', due_date date, position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.profiles enable row level security;
alter table public.organizations enable row level security;
alter table public.contacts enable row level security;
alter table public.meeting_reports enable row level security;
alter table public.kanban_stages enable row level security;
alter table public.kanban_cards enable row level security;
create policy "users_read_own_profile" on public.profiles for select using (id = auth.uid());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin' and status = 'active'); $$;
create policy "admins_manage_roster_profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());
create policy "pm_owns_organizations" on public.organizations for all using (placement_manager_id = auth.uid()) with check (placement_manager_id = auth.uid());
create policy "pm_owns_contacts" on public.contacts for all using (placement_manager_id = auth.uid()) with check (placement_manager_id = auth.uid());
create policy "pm_owns_meeting_reports" on public.meeting_reports for all using (placement_manager_id = auth.uid()) with check (placement_manager_id = auth.uid());
create policy "pm_owns_kanban_stages" on public.kanban_stages for all using (placement_manager_id = auth.uid()) with check (placement_manager_id = auth.uid());
create policy "pm_owns_kanban_cards" on public.kanban_cards for all using (placement_manager_id = auth.uid()) with check (placement_manager_id = auth.uid());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
